export const TABLE_RESIZE = 'TABLE_RESiZE'
export const CHANGE_TEXT = 'CHANGE_TEXT'
export const APPLY_STYLE = 'APPLY_STYLE'
export const CURRENT_STYLE = 'CURRENT_STYLE'
export const CHANGE_TITLE = 'CHANGE_TITLE'
export const CHANGE_DATE = 'CHANGE_DATE'
